// Shared by both deployments — the Electron shop-PC host (electron/main.ts)
// and the standalone Ubuntu host (server/index.ts) — exactly like
// server/shopName.ts, and for the same reason: this file deliberately knows
// nothing about what a "security-store" is beyond how to read one row out
// of key_value_store, so it can run standalone or embedded with zero drift.
import type { SyncDatabase } from './db'

/**
 * Reads the LAN sync token out of the key_value_store row for
 * security-store, for syncServer.ts's isAuthorized to require on every
 * /api/* request. Returns undefined (not null — matches SyncServerOptions.
 * token's shape) whenever there's no token to require: no row yet, an
 * unparsable row, or no token has ever been generated.
 *
 * Otherwise the token IS required whenever either of two independent things
 * is true:
 *
 *   - the shop's "Require token on LAN" switch (security.lanTokenRequired)
 *     is explicitly on, or
 *   - the shop already has an admin account (security.adminPasswordHash).
 *
 * The second clause used to not exist, and that was a real hole: with the
 * switch defaulting to false (see src/store/securityStore.ts's
 * lanTokenRequired doc — deliberately off so shipping this feature never
 * locked out an already-paired device), a shop that never visited Settings
 * to flip it stayed open on its own WiFi forever. /api/snapshot and
 * /api/ops would hand any unauthenticated device on the network the whole
 * dataset — adminPasswordHash, workerPasswordHash and lanToken included —
 * and POST /api/ops would accept a security-store upsert from anyone,
 * silently replacing the shop's admin password. An account existing is
 * itself the signal that this shop is no longer in its harmless bootstrap
 * window (see src/lib/auth/ensureLanToken.ts, which guarantees a token is
 * always generated by the time an account exists, so this clause is never
 * demanding a token that doesn't exist yet), and every device that's ever
 * signed in — including a follower that paired via POST /api/login rather
 * than by hand — already has it. A device that hasn't yet just sees
 * "Password needed" and can fetch it the same way: sign in with the shop's
 * username and password (server/syncServer.ts's handleLogin, which is
 * deliberately exempt from this very gate).
 *
 * The switch itself survives for exactly one remaining case: a shop that
 * wants the token required during the pre-account bootstrap window too
 * (nothing forces that; it's just available).
 *
 * The row holds a zustand-persist envelope whose state nests the security
 * object one level down — {"state":{"security":{…}},"version":0}, same
 * shape as shopName.ts reads for settings-store.
 */
export function readShopToken(db: SyncDatabase): string | undefined {
  return readToken(db, (security) => security?.lanToken)
}

/**
 * The WORKER-tier counterpart, for `createSyncServer`'s `workerToken`
 * option — same "is a token required at all" gate as readShopToken above
 * (identical two conditions, so the worker token only ever becomes
 * presentable exactly when the admin one does; there is no independent
 * "require the worker token but not the admin one" state), just reading
 * `workerLanToken` instead of `lanToken` as the value.
 *
 * Why a second token rather than reusing the admin one for both: see
 * src/store/securityStore.ts's workerLanToken doc — server/syncServer.ts's
 * validateOpBatch relies on being able to tell a worker-obtained token apart
 * from an admin-obtained one when gating security-store writes, which is
 * only possible if the two are different secrets.
 */
export function readWorkerShopToken(db: SyncDatabase): string | undefined {
  return readToken(db, (security) => security?.workerLanToken)
}

function readToken(db: SyncDatabase, pickToken: (security: any) => unknown): string | undefined {
  try {
    const raw = db.getItem('security-store')
    if (!raw) return undefined
    const parsed = JSON.parse(raw)
    const security = parsed?.state?.security
    const token = pickToken(security)
    if (typeof token !== 'string' || !token.trim()) return undefined
    if (!security?.lanTokenRequired && !security?.adminPasswordHash) return undefined
    return token
  } catch {
    return undefined
  }
}
